version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - DATABASE_HOST=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - pq_network

  backend:
    image: "dynalist.io/backend:latest"
    build: ./backend/
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - pq_network    
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  frontend:
    image: "dynalist.io/frontend:latest"
    build: ./frontend/
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    

volumes:
  pgdata:

networks:
  pq_network:
    driver: bridge